name: CI
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Fail if PR has no linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            if(!/Fixes\s+#\d+/i.test(body)) core.setFailed("PR must link an issue (Fixes #123).");
      - name: Ensure single feature type
        run: |
          TYPE=$(grep -i "Single feature type" -n .github/pull_request_template.md >/dev/null && echo "ok" || echo "missing"); echo $TYPE
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release -warnaserror
      - name: Format Check
        run: dotnet format --verify-no-changes
      - name: Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"
