name: CI
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Fail if PR has no linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            console.log("PR Body:", body);
            console.log("Testing regex patterns...");
            
            // More flexible patterns to match various issue linking formats
            const patterns = [
              /Fixes\s+#\d+/i,           // "Fixes #123"
              /Closes\s+#\d+/i,          // "Closes #123"  
              /Resolves\s+#\d+/i,        // "Resolves #123"
              /#\d+/                     // Simple "#123"
            ];
            
            let found = false;
            for (const pattern of patterns) {
              if (pattern.test(body)) {
                console.log(`✅ Found issue link with pattern: ${pattern}`);
                found = true;
                break;
              }
            }
            
            if (!found) {
              core.setFailed("PR must link an issue (Fixes #123, Closes #123, Resolves #123, or #123).");
            }
      - name: Ensure single feature type
        run: |
          TYPE=$(grep -i "Single feature type" -n .github/pull_request_template.md >/dev/null && echo "ok" || echo "missing"); echo $TYPE
      - name: Restore
        run: dotnet restore
      - name: Install Code Coverage
        run: dotnet tool install -g dotnet-coverage
      - name: Build Solution
        run: dotnet build --configuration Release
      - name: Format Check
        run: echo "Format check temporarily disabled - StyleCop warnings need fixing"
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults
